---
- name: installing packages
  hosts: all
  become: true
  
  tasks:
  - name: installing httpd in centos 
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: installing httpd ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian" 

  - name: start apache services on ubuntu
    service:
      name: apache2
      state: started    
    when: ansible_os_family ==  "Debian"

  - name: starting http services on centos
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    
  - copy:
      src: /home/ansadmin/playbooks/index.html
      dest: /var/www/html
